# -*- coding: utf-8 -*-
"""Bootstrap a REFERENCES + STUDY starter list from a folder of PDFs.

Outputs a Python snippet (corpus_refs.py) you can review and paste into
survey_slr.py, so the SLR workflow is reusable on ANY local corpus (not just
the bundled 33-paper example). Best-effort metadata extraction — you must
review author/title and fill the classification fields per paper.

Usage:
    python extract_refs.py "E:/科研/DSML+ML元建模" --out corpus_refs.py
"""
import os
import re
import glob
import argparse
import fitz  # pymupdf


def guess_meta(pdf_path):
    doc = fitz.open(pdf_path)
    txt = doc[0].get_text()
    doc.close()
    lines = [l.strip() for l in txt.splitlines() if l.strip()]
    # title: first reasonably long line that is not a bare number
    title = ""
    for l in lines[:25]:
        if len(l) >= 6 and not l.isdigit():
            title = l
            break
    # year (first 19xx/20xx on page 1)
    m = re.search(r"(?:19|20)\d{2}", txt)
    year = m.group(0) if m else ""
    # arXiv id
    am = re.search(r"arXiv[: ]*([0-9]{4}\.[0-9]{4,5})", txt)
    arxiv = am.group(1) if am else ""
    base = os.path.splitext(os.path.basename(pdf_path))[0]
    return title, year, arxiv, base


def main():
    ap = argparse.ArgumentParser(
        description="Bootstrap REFERENCES/STUDY arrays from a PDF folder.")
    ap.add_argument("folder", help="folder containing the PDFs")
    ap.add_argument("--out", default="corpus_refs.py",
                    help="where to write the starter snippet")
    args = ap.parse_args()

    pdfs = sorted(glob.glob(os.path.join(args.folder, "*.pdf")))
    if not pdfs:
        raise SystemExit("no PDFs found in %s" % args.folder)

    refs = []
    for i, p in enumerate(pdfs, 1):
        title, year, arxiv, base = guess_meta(p)
        if arxiv:
            ref = ("[J/OL]. arXiv:%s, %s." % (arxiv, year)) if year else \
                  ("[J/OL]. arXiv:%s." % arxiv)
        else:
            ref = (". %s." % year) if year else "."
        refs.append((i, base, title, year, ref))

    with open(args.out, "w", encoding="utf-8") as f:
        f.write("# auto-generated by extract_refs.py -- review author/title, "
                "then paste into survey_slr.py\n")
        f.write("REFERENCES = [\n")
        for i, base, title, year, ref in refs:
            # show guessed title as a comment for the human to verify
            f.write('    ("[%d]", "%s %s"),  # guess: %s\n'
                    % (i, base, ref, title.replace('"', "'")))
        f.write("]\n\n")
        f.write("# STUDY stubs: fill theme(A/B/C/D/SLR)/method/formal/tool/validation\n")
        f.write("STUDY = [\n")
        for i, base, title, year, ref in refs:
            yr = year if year else 0
            f.write('    (%d, "%s", %s, "?", "TODO", "TODO", "TODO", "TODO"),\n'
                    % (i, base, yr))
        f.write("]\n")

    print("wrote %s with %d entries" % (args.out, len(refs)))


if __name__ == "__main__":
    main()
